### PR TITLE
The connection details (the API key at least) must not be shown in plaintext 

### LINKED ISSUE #7: Security: the connection details are being published as plain-text build parameters
## Summary
The server-side plugin code reads the Conjur Connection details and adds these properties into the build when it is started on the server. Then the agent-side plugin code reads those parameters, establishes a connection to Conjur, and reads the secrets as necessary.
Unfortunately, the connection details remain in the ```teamcity.conjur.*``` parameters, including the API key.

## Steps to Reproduce
1. Define a Conjur connection in a TC project
2. Run a build in that project
3. After it finishes, go to Parameters
4. See the parameters e.g. ```teamcity.conjur.apiKey```

## Expected Results
The parameters should not be visible, at least not the API key.

## Actual Results (including error logs, if applicable)
API key is visible in plaintext.

## Reproducible
   * [x] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible
   
## Version/Tag number
TC 2022.04.2, Conjur plugin v0.0.1.

## Environment setup
MacOS 12.5.1

## Additional Information
TC running locally or on a dedicated server.

### PR DESCRIPTION
**Pull request by pe-tr**
### Desired Outcome

The server-side plugin code reads the Conjur Connection details and adds these properties into the build when it is started on the server. Then the agent-side plugin code reads those parameters, establishes a connection to Conjur, and uses it to read the secrets as necessary.
Unfortunately, the connection details remain in plaintext in the build's ```teamcity.conjur.*``` parameters, including the API key.
This means that anyone who happens to have access to any finished build (within a project that has the Conjur connection defined) can read the "master" key to secrets for the given login and the Conjur instance.
  
### Implemented Changes

The change in this PR means that the API key is no longer added as a regular (plain text) parameter but as a password-type parameter instead.

Please see the screenshots from the builds' parameters:
- before the fix:
connection_params_before

- after the fix:
connection_params_after

### Connected Issue/Story

Resolves #7

#### Changelog

- [x] This PR does not include user-facing changes and doesn't require a
  CHANGELOG update

#### Test coverage

- [x] This PR includes new manual tests

#### Documentation

- [x] Docs were updated in this PR - basic manual test cases were added to CONTRIBUTING.md.

#### Behavior

- [x] No behavior was changed with this PR

#### Security

- [x] These changes are part of a larger initiative with a separate security review

### CODE REVIEW

**Review by infamousjoeg — DISMISSED** [review]
LGTM

File: teamcity-server/src/main/java/com/cyberark/server/ConjurBuildStartContextProcessor.java [hunk 1]
```diff
@@ -5,38 +5,47 @@
...
 
-public class ConjurBuildStartContextProcessor implements BuildStartContextProcessor {
+public class ConjurBuildStartContextProcessor implements BuildStartContextProcessor, PasswordsProvider {
 
-    // This method will return one SProjectFeatureDescriptor that represents the CyberArk Conjur Connection
-    //   provided in the project Connections. This method will return null if no Connection can be found and will throw
-    //   a MultipleConnectionsReturnedException if more than one connection was found.
-    private SProjectFeatureDescriptor getConnectionType(SProject project, String providerType) throws MultipleConnectionsReturnedException {
-        List<SProjectFeatureDescriptor> connections = new ArrayList<SProjectFeatureDescriptor>();
+    // This method will params that represents the CyberArk Conjur Connection
```
Comment (jtuttle) [inline teamcity-server/src/main/java/com/cyberark/server/ConjurBuildStartContextProcessor.java:19]: Looks like something is missing here, maybe just the word "return"?

File: teamcity-server/src/main/java/com/cyberark/server/ConjurBuildStartContextProcessor.java [hunk 2]
```diff
@@ -47,39 +56,37 @@ private BuildProblemData createBuildProblem(SBuild build, String message) {
...
+        if (conjurConnParams != null) {
+            for (Map.Entry<String, String> kv : conjurConnParams.entrySet()) {
+                context.addSharedParameter(kv.getKey(), kv.getValue());
+            }
+        }
+    }
 
+    // the purpose of this method is to mark a given param as password-type
+    @Override
+    public Collection<Parameter> getPasswordParameters(SBuild build) {
```
Comment (jtuttle) [inline teamcity-server/src/main/java/com/cyberark/server/ConjurBuildStartContextProcessor.java:76]: How is this not adding every single param as a password type? I don't see any place where you're calling out the API key specifically, but also I'm not super familiar with modern Java. :)

**Review by jtuttle — CHANGES_REQUESTED** [review]

File: teamcity-server/src/main/java/com/cyberark/server/ConjurBuildStartContextProcessor.java (hunk 2 above)
Comment (pe-tr) [reply teamcity-server/src/main/java/com/cyberark/server/ConjurBuildStartContextProcessor.java:76]: It's a decision to make - which of those parameters are sensitive enough to be marked as password-type. Before this PR, none of them was marked as such. The api key is definitely sensitive enough, the remaining ones probably not (they don't have much value without the key) - therefore i'm leaving them as they are, i.e. plaintext.

Regarding the implementation: the BuildStartContextProcessor (updateParameters() method) is used to *add* the params, the *PasswordsProvider* (getPasswordParameters() method) only *marks* the already added params as read-only. That's how i understand the advisory i received from JetBrains (thanks you JB!)

File: teamcity-server/src/main/java/com/cyberark/server/ConjurBuildStartContextProcessor.java (hunk 1 above)
Comment (pe-tr) [reply teamcity-server/src/main/java/com/cyberark/server/ConjurBuildStartContextProcessor.java]: Thank you - fixed.

**Review by jtuttle — APPROVED** [review]
